default: &default
  adapter: mysql2
  host: <%= ENV['DATABASE_ENDPOINT'] %>
  encoding: utf8
  pool: 5
test:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
