name: CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.7.0 ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ankane/setup-mysql@v1
        with:
          mysql-version: 8.0
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client libpq-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - run: yarn install
      - run: yarn test
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Move database.ci.yml
        run: cp config/database.ci.yml config/database.yml
      - name: Run tests
        env:
          DATABASE_NAME: actions_test
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: ""
          DATABASE_ENDPOINT: 127.0.0.1
          RAILS_ENV: test
        run: bin/rails db:setup spec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/capybara
          if-no-files-found: ignore